create table Players
(
    ID   int primary key generated by default as identity,
    Name varchar
);

create table Matches
(
    ID      int primary key generated by default as IDENTITY,
    Player1 int,
    Player2 int,
    Winner  int references Players on Id,
    FOREIGN KEY (Player1) REFERENCES Players (ID),
    FOREIGN KEY (Player2) REFERENCES Players (ID),
    FOREIGN KEY (Winner) REFERENCES Players (ID)
);

INSERT INTO Players(Name) VALUES ('Timur'), ('Dima'), ('Denis'), ('Katya'), ('Anna');

INSERT INTO Matches(Player1, Player2, Winner) VALUES (1, 2, 1), (1, 3, 3), ( 2, 3, 3), (4, 5, 5), (1, 5, 1);